title:              뗄깜 블로그
email:              n4oahdev@gmail.com
description:        n4oah의 개발 블로그 입니다.
author:             n4oah
baseurl:            ""
url:                "https://n4oah.github.io"

# Social Profiles
twitter_username:   
github_username:    n4oah
facebook_username:  
instagram_username:  ghwl0
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-170226089-1 # out your google-analytics code

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-babel

babel_js_extensions: 'js'

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

timezone: Asia/Seoul